arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - yaw_joint
      - shoulder_joint
      - elbow_joint
      - roll_joint
    state_publish_rate: 20

gripper_controller:
    type: "position_controllers/JointTrajectoryController"
    joints: 
      - clamp_joint
    state_publish_rate: 20

